### ISSUE TITLE
Wrong dependency route

### ISSUE THREAD

**Issue by thir13en** [BioPhoton/angular-star-rating#72] opened 2018-02-26 08:04 UTC
## I'm submitting a...

<pre><code>
[ X ] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

Wrong route for css-star-rating dependency. Just installed angular star rating version 3.0.8, which installed the dependecy css-star-rating v.1.2.4. The scss file from the angular-star-rating is importing "@import "~css-star-rating/dist/scss/star-rating.scss", which results in an error thrown by the sass loader since the star rating scss is actually in the route ~css-star-rating/scss/star-rating.scss".

## Expected behavior

Correct route to import the scss file.

## Minimal reproduction of the problem with instructions

Installed project dependencies via npm install and started via npm start, the following error is thrown in the console:
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
Module build failed:
<pre><code>
@import "~css-star-rating/dist/scss/star-rating.scss";
^
      File to import not found or unreadable: ~css-star-rating/dist/scss/star-rating.scss.
Parent style sheet: /home/santiloopz/repos/exo-frontend/node_modules/angular-star-rating/assets/scss/star-rating.scss
      in /home/santiloopz/repos/exo-frontend/node_modules/angular-star-rating/assets/scss/star-rating.scss (line 1, column 1)
</code></pre>

## Environment

<pre><code>
Library version: 3.0.8
Angular version: 5.2.6

**Comment by jerryxuxuxu** [comment] 2018-02-26 08:23
Same issue breaks my production build caused by css-star-rating updated to 1.2.4. Have to install 1.1.3 version separately for the time being.

**Comment by Neoluis10** [comment] 2018-02-27 05:09
Hi @thir13en and @jerryxuxuxu Have you found a workaround for this issue? If so, please let me know. I'm having the same problem. Thank you in advance!

**Comment by dhyey35** [comment] 2018-02-27 06:27
@BioPhoton Can you please fix this issue ? It is breaking our production build too.

**Comment by thir13en** [comment] 2018-02-27 08:18
@Neoluis10 , I found a workaround, yes. thou is not ideal. I manually deleted the dist/ from the import in the library's scss, so:
@import "~css-star-rating/dist/scss/star-rating.scss"; -> 
@import "~css-star-rating/scss/star-rating.scss";

But this is something that might be overridden by later dependencies installs or updates and only works locally.

Otherwise, check  @jerryxuxuxu comment.

**Comment by dhyey35** [comment] 2018-02-27 10:10
@thir13en I think the better way would be importing the scss file of `css-star-rating` directly in your `styles.scss` as the scss file of `angular-star-rating` just includes that one line, and removing import of angular-star-rating's scss file. This way we will not need to modify the library's scss and so no worries about the file being overriden by later dependency installs

**Comment by thir13en** [comment] 2018-02-27 11:03
Thanks @dhyey35, I think your proposal is a more satisfactory approach until this is solved. Cheers!

[EDIT]: Actually thinking about it, if you remove the import from the scss it will also be overridden in later installs, so the problem of the sass-loader compile time error will persist.

**Comment by dhyey35** [comment] 2018-02-27 12:19
By 

> removing import of angular-star-rating's scss file

I meant removing `@import "../node_modules/angular-star-rating/assets/scss/star-rating"` from your project's `styles.scss` and replacing it with `@import "../node_modules/css-star-rating/dist/scss/star-rating.scss";` making **NO changes in any of library's files**. So there will be no issues in later install as we are not modifying anything inside `node_modules`

**Comment by thir13en** [comment] 2018-02-27 14:15
Actually there should be, because even thou you import the file in your stylesheet, in the library you still have an import of a file with the wrong route, which will throw a compile time error.

**Comment by Neoluis10** [comment] 2018-02-27 15:54
The workaround that @jerryxuxuxu suggested worked for me! At first I didn't completely understand the steps I needed to do, but after looking closely to the `package-lock.json`, I noticed that `angular-star-rating` has a dependency with `css-star-rating` (version 1.2.4), so I had to execute the following command: 
`npm install css-star-rating@1.1.3`
And now the error is gone! Thanks to @jerryxuxuxu  and @thir13en for your help.

**Comment by dhyey35** [comment] 2018-02-28 04:58
@thir13en I did it in my project and there is no error at compile time. I think because there is no reference to angular-star-rating's scss file it is not included at compile time.

**Comment by thir13en** [comment] 2018-03-01 10:12
I see what you mean now @dhyey35

**Comment by BioPhoton** [comment] 2018-03-30 15:13
Hi @thir13en. Could you check the latest version? it should be fixed there

**Comment by robjean9** [comment] 2018-04-03 12:54
I test today in the latest version, and keeping not working with the same error

**Comment by gerasiie** [comment] 2018-04-06 07:43
Hi @robjean9. You most likely have a reference to the missing file form your own styles.scss (styles.css) file.

**Comment by BioPhoton** [comment] 2018-04-07 15:30
ould you reproduce this in stackbliz or so? 
I have created a basic example to edit [here](https://stackblitz.com/edit/angular-star-rating-demo)

**Comment by BioPhoton** [comment] 2018-04-20 20:59
This is fixed in the latest version

**Closed as completed by BioPhoton** 2018-04-20 20:59 UTC
